### PR TITLE
Added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by zeesh-ali**
Created a new file and added the link to point to the existing CONTRIBUTING.md file.

### CODE REVIEW

**Comment by zeesh-ali** [comment]
Hi Madie, please let me know if it worked correctly.

**Comment by madiedgar** [comment]
I'm going to close this one, as we merged #26 🎉

**Comment by zeesh-ali** [comment]
Thank you so much. Had my best intentions hope I have not increased your
work. Thank you again.

**Comment by madiedgar** [comment]
No worries!! Thank you for giving it your best 😄 I appreciate your thoughtfulness more than anything ❤️

**Pull request closed without merging**
