### PR TITLE
Add contributing.md file

### PR DESCRIPTION
**Pull request by zeesh-ali**
Added the contributing.md file with it's data with the link.

### CODE REVIEW

**Comment by madiedgar** [comment]
Hey @zeesh-ali don't worry about this error. It's unrelated to your addition. I need to look into the error though 🙊

**Comment by madiedgar** [comment]
Congrats on merging your first pull request! 🎉🎉🎉 ❤️ **THANK YOU THANK YOU THANK YOU** ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R) only given to those who have chosen to give back.
We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍

**Comment by madiedgar** [comment]
@all-contributors please add @zeesh-ali for doc

**Comment by zeesh-ali** [comment]
@madiedgar Thank you for you support, I hope I did not end up increasing your work instead. Thank you once again !!!

**Comment by madiedgar** [comment]
No, thank you @zeesh-ali!! Appreciate you!

**Pull request merged**
